### PR TITLE
remove useless NimbusBlockImport

### PR DESCRIPTION
**Pull request by RomarQ**
This change was authored by @librelois and is part of the work related to the transaction pool improvements on moonbeam.

Historically aura was overcharging fork strategy for parachain at block import, but it's seems no longer necessary.

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
Won't parachain nodes import blocks as best this way? Is that desired now?

**Comment by librelois** [comment]
It was a suggestion from parity but for some reasons it doesn't work

**Comment by JoshOrndorff** [comment]
What are you trying to do? Maybe I can share an idea or two.

**Comment by RomarQ** [comment]
> What are you trying to do? Maybe I can share an idea or two.

Context for the change: https://github.com/paritytech/polkadot-sdk/issues/4333#issuecomment-2085464081

**Comment by crystalin** [comment]
A bit more context to @JoshOrndorff (if you are still around, "Hi" btw :p). Right now import is done from blocks marked as "best" by the relay, but that is slow for user interaction (tx take like 18s to be "validated") so we are now using the "imported" block directly.

**Review by Agusrodri — APPROVED** [review]

**Comment by RomarQ** [comment]
@girazoki Are you fine with the changes included in this PR?

**Pull request merged**
